version: '3'

services:
  vgt-saga-broker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: broker
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - messaging

networks: 
    messaging:
      driver: bridge